version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/current/
  - source: /code.css
    destination: /var/www/html/current/
hooks:
  BeforeInstall:
    - location: scripts/before_start
      timeout: 300
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
